# name: lan-pipeline-2
# channels:
#     - conda-forge
#     - defaults
# dependencies:
#     - python=3.11
#     - pip
#     - pip:
#         - "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
#         - torch --index-url https://download.pytorch.org/whl/cu118
#         - torchvision --index-url https://download.pytorch.org/whl/cu118
#         - torchaudio --index-url https://download.pytorch.org/whl/cu118
#         - frozendict
#         - pyyaml
#         - jupyter
#         - ssm-simulators
#         - lanfactory

# THIS IS DEFUNCT FOR NOW, HAVE TO GET THE PIP INSTALL INTRICACIES RIGHT